import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bodyLayout`}
      >
        <header className={"navbar"}>
          <nav className={"navLeft"}>
            <a href="/" className={"navLink"}>Home</a>
            <a href="/game" className={"navLink"}>Game</a>
            <a href="" className={"navLink"}>Roadmap</a>
            <a href="" className={"navLink"}>Team</a>
          </nav>

          <nav className={"navRight"}>
            <a href="" className={"navLink"}>Login</a>
            <a href="" className={"navLink"}>Create Account</a>
          </nav>
        </header>
        <main className="page">
          {children}
        </main>

        <footer className="footer">
          <p>© {new Date().getFullYear()} Brain Eaters - All rights reserved.</p>
          <a href="" className="footerLink">Contact Us</a>
        </footer>
      </body>
    </html>
  );
}
